spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop; # MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create  # create: app 실행 시점에 entity 전부 지우고 다시 만들기
    properties:
      hibernate:
#        show_sql: true -> 여기는 system out으로 보임
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 쿼리 추적 기능
